name: ZurixGens
version: ${project.version}
main: dev.risas.zurixgens.ZurixGens
api-version: '1.13'
author: Risas
depend: [Vault]
softdepend: [SuperiorSkyblock2]
commands:
  generator:
    description: "Generator Command"
    aliases: ["gen", "gens"]
  sell:
    description: "Sell Command"
    aliases: ["sellall"]
  statistic:
    description: "Statistic Command"
    aliases: ["stats", "stat", "statistics", "estadisticas"]
  event:
    description: "Event Command"
    permission: "zurixgens.command.event"
  pickupgens:
    description: "Pickup Gens Command"